[build]
builder = "NIXPACKS"
buildcommand = "go build -o main ./cmd/web"

[deploy]
startCommand = "./main"

[variables]
MONGODB_URI = "your-atlas-connection-string"
SESSION_SECRET = "your-secret-key"
